### ISSUE TITLE
Feedback of supplierdata to customer ERP

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/businessnetwork#33] opened 2017-07-14 14:19 UTC
Deka use-case: onboarding the existing known deka suppliers 

Deka exports from SAP to CSV, we import into campaign(s)  (Norbert has CSV file from Kessler)

As soon as suppliers onboard, we get additional information, e.g. email, personal contact details etc.
We need to feed back that supplier data in to SAP
Supplier data is in supplier service, user data in user service, customer specific supplierId is in einvoice-send

**Comment by gr4per** [comment] 2017-07-14 14:53
We can do type oneTimeUse for the existing invitationCodes (set as default) and also implement checking that prevents the same oneTimeUse code to be used for multiple users (i.e. if userId has been set, then dont allow to use the code again).

**Comment by nczeranka** [comment] 2017-07-24 10:36
OpusCapita/user#45
 OpusCapita/einvoice-send#26

**Comment by nczeranka** [comment] 2017-07-24 11:17
Duplicate of OpusCapita/businessnetwork/issues/34

**Closed by nczeranka** 2017-07-24 11:17 UTC
Labels: mvp_deka
